In [4]:
dados = {
    "Nome" : [
        "Molodoy",
        "Fallen",
        "KS"
        ], 
    "Idade" : [22, 35, 26],
    "Profissão" : ["AWP","Professor","AK"]
}

In [5]:
import pandas as pd

df = pd.DataFrame(dados)

In [4]:
df

      Nome  Idade  Profissão
0  Molodoy     22        AWP
1   Fallen     35  Professor
2       KS     26         AK

In [5]:
type(df)

pandas.core.frame.DataFrame

In [6]:
df["Nome"]

0    Molodoy
1     Fallen
2         KS
Name: Nome, dtype: object

In [8]:
type(df["Nome"])

pandas.core.series.Series

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Nome       3 non-null      object
 1   Idade      3 non-null      int64
 2   Profissão  3 non-null      object
dtypes: int64(1), object(2)
memory usage: 204.0+ bytes

In [10]:
df.dtypes

Nome         object
Idade         int64
Profissão    object
dtype: object

In [11]:
df["Idade"].mean()

np.float64(27.666666666666668)

In [12]:
df["Idade"].max()

35

In [13]:
df.describe()

           Idade
count   3.000000
mean   27.666667
std     6.658328
min    22.000000
25%    24.000000
50%    26.000000
75%    30.500000
max    35.000000

In [6]:
df.describe(exclude="number")

           Nome Profissão
count         3         3
unique        3         3
top     Molodoy       AWP
freq          1         1